esphome:
  name: laserfilter
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "backspace IoT"
  password: "changeme"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "changeme"

ota:
  password: "changeme"

mqtt:
  broker: mqtt.core.bckspc.de

light:
  - platform: neopixelbus
    type: GRB
    pin: D8
    num_leds: 6 
    name: "laserfilterstatusstripe"
    id: laserfilterstatusstripe
    method: BIT_BANG #We use the first WS2812 LED to cleanup the signal

sensor:
  # First laser stage
  - platform: mqtt_subscribe
    name: "Pressure 1"
    id: laser1
    topic: project/laser/sensor/1/pressure
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                return id(laser1).state < 983; 
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 0%
                  blue: 0%
                  range_from: 1
                  range_to: 1
        - if:
            condition:
              lambda: |-
                return id(laser1).state > 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 100%
                  blue: 0%
                  range_from: 1
                  range_to: 1
        - if:
            condition:
              lambda: |-
                return id(laser1).state > 984;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 0%
                  green: 100%
                  blue: 0%
                  range_from: 1
                  range_to: 1
  # Second laser stage
  - platform: mqtt_subscribe
    name: "Pressure 3"
    id: laser3
    topic: project/laser/sensor/3/pressure
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                return id(laser3).state < 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 0%
                  blue: 0%
                  range_from: 2
                  range_to: 2
        - if:
            condition:
              lambda: |-
                return id(laser3).state > 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 100%
                  blue: 0%
                  range_from: 2
                  range_to: 2
        - if:
            condition:
              lambda: |-
                return id(laser3).state > 984;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 0%
                  green: 100%
                  blue: 0%
                  range_from: 2
                  range_to: 2
  # Third laser stage
  - platform: mqtt_subscribe
    name: "Pressure 4"
    id: laser4
    topic: project/laser/sensor/4/pressure
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                return id(laser4).state < 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 0%
                  blue: 0%
                  range_from: 3
                  range_to: 3
        - if:
            condition:
              lambda: |-
                return id(laser4).state > 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 100%
                  blue: 0%
                  range_from: 3
                  range_to: 3
        - if:
            condition:
              lambda: |-
                return id(laser4).state > 984;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 0%
                  green: 100%
                  blue: 0%
                  range_from: 3
                  range_to: 3
  # Fourth laser stage
  - platform: mqtt_subscribe
    name: "Pressure 5"
    id: laser5
    topic: project/laser/sensor/5/pressure
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                return id(laser5).state < 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 0%
                  blue: 0%
                  range_from: 4
                  range_to: 4
        - if:
            condition:
              lambda: |-
                return id(laser5).state > 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 100%
                  blue: 0%
                  range_from: 4
                  range_to: 4
        - if:
            condition:
              lambda: |-
                return id(laser5).state > 984;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 0%
                  green: 100%
                  blue: 0%
                  range_from: 4
                  range_to: 4
    # Fifth laser stage
  - platform: mqtt_subscribe
    name: "Pressure 7"
    id: laser7
    topic: project/laser/sensor/7/pressure
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                return id(laser7).state < 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 0%
                  blue: 0%
                  range_from: 5
                  range_to: 5
        - if:
            condition:
              lambda: |-
                return id(laser7).state > 983;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 100%
                  green: 100%
                  blue: 0%
                  range_from: 5
                  range_to: 5
        - if:
            condition:
              lambda: |-
                return id(laser7).state > 984;
            then:
              - light.addressable_set:
                  id: laserfilterstatusstripe
                  red: 0%
                  green: 100%
                  blue: 0%
                  range_from: 5
                  range_to: 5
